stages:
  - build_stage
  - depoly_stage


build:
  image: node
  stage: build_stage
  script:
#   - apt update -y
#   - apt install npm -y
    - npm install 

depoly:
  image: node
  stage: depoly_stage
  script:
#    - apt update -y
#    - apt install nodejs -y
    - node app.js > /dev/null 2>&1 &
